### ISSUE TITLE
fail to run the inference

### ISSUE THREAD

**Issue by DashingPanda** [minghanz/trafcam_3d#5]
When I run the inference according to the instruction in repo of "minghanz/yolov3", there is something wrong like the picture attached to.
![Uploading Screen Shot 2022-10-10 at 15.33.20.png…]()

**Comment by DashingPanda** [comment]
trafcam_3d) root@6a269f16f611:/mnt/data_cfl/Projects/trafcam_3d/yolov3# bash run_detect.sh 
Namespace(agnostic_nms=False, augment=False, cfg='./cfg/yolov3-spp-rboxttdv180.cfg', classes=None, conf_thres=0.2, device='', dual_view=True, fourcc='mp4v', half=False, half_angle=True, img_size=448, iou_thres=0.2, names='./data/bev_network.names', output='/mnt/data_cfl/Projects/trafcam_3d/yolov3/output', rotated=True, rotated_anchor=True, save_txt=True, single_cls=True, source='/mnt/data_cfl/Projects/trafcam_3d/yolov3/source/videos', tail=True, tail_inv=False, use_mask=True, view_img=False, weights='/mnt/data_cfl/Projects/trafcam_3d/yolov3/weights/best_ra_tail_180_dv.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device1 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device2 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device3 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device4 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device5 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device6 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)
           device7 _CudaDeviceProperties(name='Tesla V100-SXM2-32GB', total_memory=32510MB)

Initialize preceding Conv2d() bias (https://arxiv.org/pdf/1708.02002.pdf section 3.3)
Initialize preceding Conv2d() bias (https://arxiv.org/pdf/1708.02002.pdf section 3.3)
Initialize preceding Conv2d() bias (https://arxiv.org/pdf/1708.02002.pdf section 3.3)
Model Summary: 354 layers, 8.23524e+07 parameters, 8.23524e+07 gradients
self.img_size 448
self.img_size 448
  0%|                                                                                                                    | 0/205584 [00:00<?, ?it/s]
####################################################################################################
The path is: /mnt/data_cfl/Projects/trafcam_3d/yolov3/source/videos/bev.avi
  0%|                                                                                                                    | 0/205584 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "detect.py", line 296, in <module>
    detect()
  File "detect.py", line 107, in detect
    for frame_i, sample_batch in enumerate(pbar):
  File "/root/Applications/anaconda3/envs/trafcam_3d/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/mnt/data_cfl/Projects/trafcam_3d/yolov3/utils/datasets.py", line 76, in __next__
    path_bev, img_bev, img0_bev, invalid_mask, cap_bev, H_world_bev = next(self.dual_first)
  File "/mnt/data_cfl/Projects/trafcam_3d/yolov3/utils/datasets.py", line 236, in __next__
    raise ValueError("file not recognized: {}".format(path))
ValueError: file not recognized: /mnt/data_cfl/Projects/trafcam_3d/yolov3/source/videos/bev.avi
